name: 'camera'
class: 'Camera'
index: 0
hfov: 100
vfov: 56.25
fps: 30
height: 1080
width: 1920
depth: 3
x: -0.21 # meters forward from front axle
y:  0.00 # meters left from center of vehicle. Assume zero for now
z:  0.43 # meters up from floor
roll:   0.0 # degrees left tilt. Assume zero for now
pitch: -28.0 # degrees incline
yaw:    0.0 # degrees left turn. Assume zero for now
resize: 0.25
recrop: None
