brain:
  path: brain-clone.yaml
camera:
  path: camera-OV2710.yaml
joystick:
  keyboard_names:
    - keyboard
    - kbd
    - logitech k400 plus
    - gaming kb
  deadzone: 8
servo:
  path: servo-micromaestro.yaml
writer: {}
