brain:
  path: brain-clone.yaml
camera:
  index: 0
  hfov: 62.2
  vfov: 48.8
  fps: 21
  capture_height: 2464
  capture_width: 3264
  height: 616
  width: 816
  depth: 3
  flip_method: 2
  x: -0.01 # meters forward from front axle
  y:  0.00 # meters left from center of vehicle. Assume zero for now
  z:  0.12 # meters up from floor
  roll:   0.0 # degrees left tilt. Assume zero for now
  pitch:  0.0 # degrees incline
  yaw:    0.0 # degrees left turn. Assume zero for now
  mode: csi
  quality: 80
imu: {}
joystick:
  deadzone: 8
  speed_normalizer: 0.3
  steer_normalizer: 1.0
servo:
  speed_index: 1
  speed_min: -0.5
  speed_max: 0.5
  speed_reversed: false
  steer_index: 0
  steer_min: -0.9
  steer_max: 0.9
  steer_reversed: true
writer: {}
