class: 'Clone'

# Dataset creation parameters
create:
  data_folders: ['train-2017-oakland']
  train_chance: 0.8
  n_perts: 1
  perts:
    shift:
      max: 0.0 # meters
      fudge: 0.5
      timedecay: 1.0
    rotate:
      max: 0 # degrees
      fudge: 0.02
      timedecay: 1.0
    
# Training related parameters
train:
  prepare:
    - {name: 'colorjitter', brightness: 0.5, contrast: 0.5, saturation: 0.5, hue: 0.1}

# Where to cut out the patch
thumb:
  component: 'camera_front'
  hfov: 75
  vfov: 18.75
  height: 32
  width: 128
  depth: 3
  x: -0.21
  y: 0.0
  z: 0.43
  roll: 0
  pitch: -10
  yaw: 0

# The status we feed into the network
status: []

# States we will predict
predict:
  - {name: 'speed', field: 'speed', time_offset: -0.2, scale: 1 }
  - {name: 'steer', field: 'steer', time_offset: -0.2, scale: 1 }
