name: 'clonefixspeed'
class: 'CloneFixSpeed'

# Training related parameters
create:
  data_folders: ['train']
  train_chance: 0.9
  n_perts: 1
  perts:
    shift:
      max: 0.0 # meters
      fudge: 0.5
      timedecay: 1.0
    rotate:
      max: 0 # degrees
      fudge: 0.02
      timedecay: 1.0

# Training related parameters
train:
  prepare:
    - {name: 'colorjitter', brightness: 0.5, contrast: 0.5, saturation: 0.5, hue: 0.1}

# What we expect for input from the camera
thumb:
  component: 'camera_front'
  hfov: 5
  vfov: 5
  height: 64
  width: 64
  depth: 3
  x: -0.21
  y: 0.0
  z: 0.43
  roll: 0
  pitch: -28
  yaw: 0

# The status we feed into the network
status: []

# States we will predict
predict:
  - {field: 'steer', delay: 0.3, scale: 1 }
#  - {field: 'shift', scale: 10 }
#  - {field: 'rotate', scale: 0.1 }
